name: ASP.NET app deploy to Azure

on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    - name: Run a one-line script
      run: dir
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Restore
      run: nuget restore
      
    # use msbuild to build VS solution 
    - name: Build solution
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" WebApplication1.sln -t:rebuild /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="WebAppContent"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" WebApplication1.sln -t:rebuild /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="WebAppContent"
    
    - name: Run a one-line script
      run: dir
    
    - name: Run a one-line script
      run: dir WebApplication1

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: aspnetweb # Replace with your app name
        publish-profile: ${{ secrets.publishProfile }} # Define secret variable in repository settings as per action documentation
        package: 'WebApplication1/WebAppContent/'
